default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'postgres'
  timeout: 5000

development:
  <<: *default
  database: sqldev_development

test:
  <<: *default
  database: sqldev_test